import os
import glob

# Clean images from the root directory that may have been generated by interpret.py

files = glob.glob("../*.png") + glob.glob("../*.jpg") + glob.glob("../*.jpeg")

for file in files:
    os.remove(file)